apiVersion: v1
kind: Service
metadata:
  name: mybank-kafka
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
      protocol: TCP
      name: client
  selector:
    app: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
