apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mybank-kafka
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: mybank-kafka
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kafka
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: client
            - containerPort: 9093
              name: controller
          env:
            # KRaft mode — без Zookeeper
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@mybank-kafka-0.mybank-kafka.{{ .Release.Namespace }}.svc.cluster.local:9093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://mybank-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: CLUSTER_ID
              value: {{ .Values.kraft.clusterId | quote }}
            # Настройки топиков
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            # Persistence
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
          startupProbe:
            tcpSocket:
              port: 9092
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9092
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            periodSeconds: 15
            failureThreshold: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
