apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-transfer-service
  labels:
    app: transfer-service
    app.kubernetes.io/name: transfer-service
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://{{ .Values.global.postgresql.host }}:{{ .Values.global.postgresql.port }}/{{ .Values.global.postgresql.database }}?currentSchema={{ .Values.db.schema }}"
  DB_USER: {{ .Values.global.postgresql.username }}
  DB_PASSWORD: {{ .Values.global.postgresql.password }}
  OAUTH2_CLIENT_SECRET: {{ .Values.keycloak.clientSecret }}
