apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transfer-service
  labels:
    app: transfer-service
    app.kubernetes.io/name: transfer-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app: transfer-service
    app.kubernetes.io/instance: {{ .Release.Name }}
