image:
  repository: mybank/yp-mybank-gateway
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8090

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Порты бэкенд-сервисов (для маршрутизации через K8s DNS)
routes:
  accountsService:
    port: 8080
  cashService:
    port: 8080
  transferService:
    port: 8080
  notificationsService:
    port: 8080
