# ============================================================
# MyBank — Глобальные настройки зонтичного Helm-чарта
# ============================================================

global:
  # Хостнейм приложения (добавьте в /etc/hosts: 127.0.0.1 mybank.local keycloak.mybank.local)
  appHost: mybank.local
  keycloakHost: keycloak.mybank.local

  # PostgreSQL
  postgresql:
    host: mybank-postgresql
    port: 5432
    database: mybank
    username: mybank
    password: mybank_password

  # Keycloak (внешний URL — через Ingress, для браузера и OAuth2 redirect)
  keycloak:
    externalUrl: "http://keycloak.mybank.local"
    issuerUri: "http://keycloak.mybank.local/realms/mybank"
    internalUrl: "http://mybank-keycloak:8080"
    jwkSetUri: "http://mybank-keycloak:8080/realms/mybank/protocol/openid-connect/certs"

  imageRegistry: ""

postgresql:
  enabled: true

keycloak:
  enabled: true

gateway-service:
  enabled: true

front-ui:
  enabled: true

accounts-service:
  enabled: true

cash-service:
  enabled: true

transfer-service:
  enabled: true

notifications-service:
  enabled: true