image:
  repository: quay.io/keycloak/keycloak
  tag: "25.0.2"
  pullPolicy: IfNotPresent

replicaCount: 1

admin:
  username: admin
  password: ""  # передаётся через values-local.yaml или --set

service:
  port: 80

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations: {}
