{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-front-ui
  labels:
    app: front-ui
    app.kubernetes.io/name: front-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.appHost }}
      http:
        paths:
          # API-запросы → Gateway Service
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway-service
                port:
                  number: 8090
          # Всё остальное → Front UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-front-ui
                port:
                  number: {{ .Values.service.port }}
{{- end }}
