apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-realm-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  KC_SECRET_ACCOUNTS:  {{ index .Values "accounts-service" "keycloak" "clientSecret" | quote }}
  KC_SECRET_CASH:      {{ index .Values "cash-service" "keycloak" "clientSecret" | quote }}
  KC_SECRET_TRANSFER:  {{ index .Values "transfer-service" "keycloak" "clientSecret" | quote }}
  KC_SECRET_FRONTEND:  {{ index .Values "front-ui" "keycloak" "clientSecret" | quote }}
