apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybank-accounts-service
  labels:
    app: accounts-service
    app.kubernetes.io/name: accounts-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: accounts-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: accounts-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: accounts-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_CONFIG_IMPORT
              value: "file:/config/application-k8s.yml"
          envFrom:
            - secretRef:
                name: mybank-accounts-service
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: mybank-accounts-service
