apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybank-zipkin
  labels:
    app: zipkin
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zipkin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: zipkin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9411
              name: http
          env:
            - name: STORAGE_TYPE
              value: {{ .Values.storage.type }}
            {{- if eq .Values.storage.type "elasticsearch" }}
            - name: ES_HOSTS
              value: {{ .Values.storage.esHosts }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}