apiVersion: v1
kind: Service
metadata:
  name: mybank-zipkin
  labels:
    app: zipkin
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9411
  selector:
    app: zipkin
    app.kubernetes.io/instance: {{ .Release.Name }}