apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 5000
              name: tcp
          env:
            - name: LS_JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 5044
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pipeline
          configMap:
            name: logstash-pipeline
