apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  realm-mybank.json: |-
    {{ .Files.Get "realm-mybank.json" | nindent 4 }}
