apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-notifications-service
  labels:
    app: notifications-service
    app.kubernetes.io/name: notifications-service
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:{{ .Values.global.postgresql.port }}/{{ .Values.global.postgresql.database }}?currentSchema={{ .Values.db.schema }}"
  DB_USER: {{ .Values.global.postgresql.username }}
  DB_PASSWORD: {{ .Values.global.postgresql.password }}
