apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front-ui
  labels:
    app: front-ui
    app.kubernetes.io/name: front-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: front-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: front-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: front-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_CONFIG_IMPORT
              value: "file:/config/application-k8s.yml"  
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-front-ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
           readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
             periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
             periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-front-ui
