apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: monitoring
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9411
              name: http
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx512m -XX:+ExitOnOutOfMemoryError"
            - name: STORAGE_TYPE
              value: {{ .Values.storage.type | quote }}
            - name: ES_HOSTS
              value: {{ .Values.storage.esHost | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 45
            periodSeconds: 30
